const $=s=>document.querySelector(s),app=$('#app'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let session,state,pending=false,network=true,offset=0,audio=null,lastTurn=null,lastPhase=null,polling=false;let sound=localStorage.getItem('party-sound')!=='off';try{session=JSON.parse(sessionStorage.getItem('party-session-v2'))}catch{}
const badge=s=>'<span class="badge">'+esc(s)+'</span>';const btn=(a,t,extra='',cls='quiet')=>'<button class="'+cls+'" data-action="'+a+'" '+extra+'>'+t+'</button>';
function soundLabel(){$('#sound').textContent='Sound: '+(sound?'on':'off')}soundLabel();
function tone(win=false){if(!sound||!audio)return;try{[0,1,2].forEach((i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=(win?[523,659,784]:[523,659,523])[i];g.gain.setValueAtTime(.07,audio.currentTime+i*.14);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+i*.14+.16);o.connect(g);g.connect(audio.destination);o.start(audio.currentTime+i*.14);o.stop(audio.currentTime+i*.14+.17);});}catch{}}
document.addEventListener('click',()=>{try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume()}catch{}},{once:false});$('#sound').onclick=()=>{sound=!sound;localStorage.setItem('party-sound',sound?'on':'off');soundLabel()};
function celebrate(){tone(true);if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<50;i++){const c=document.createElement('div');c.className='confetti';c.style.left=Math.random()*100+'vw';c.style.background=['#bd9aff','#65d9a6','#ffd080','#ff7d8f'][i%4];c.style.animationDelay=Math.random()*.7+'s';document.body.append(c);setTimeout(()=>c.remove(),4000)}}
async function request(action,extra={},quiet=false){if(!quiet)$('#error').textContent='';const res=await fetch('/.netlify/functions/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...session,action,...extra})});const data=await res.json();if(!res.ok)throw Error(data.error);if(data.session){session=data.session;sessionStorage.setItem('party-session-v2',JSON.stringify(session));}if(data.state)update(data.state);return data;}
function update(s){offset=s.serverNow-Date.now();state=s;network=true;$('#connection').textContent='Connected · Room '+s.code;if(s.phase==='write'&&s.author===s.me&&lastTurn!==s.turnId)tone();if(s.phase==='finished'&&lastPhase!=='finished')celebrate();lastTurn=s.turnId;lastPhase=s.phase;render();}
function saveInputs(){const values={};app.querySelectorAll('input,textarea,select').forEach(e=>{if(e.id)values[e.id]=e.value});const focus=document.activeElement;return {values,focus:focus?.id,start:focus?.selectionStart,end:focus?.selectionEnd,details:[...app.querySelectorAll('details[id]')].filter(e=>e.open).map(e=>e.id)}}
function restoreInputs(d){for(const [id,value]of Object.entries(d.values)){const e=document.getElementById(id);if(e)e.value=value}for(const id of d.details){const e=document.getElementById(id);if(e)e.open=true}if(d.focus){const e=document.getElementById(d.focus);if(e){e.focus({preventScroll:true});try{e.setSelectionRange(d.start,d.end)}catch{}}}}
function landing(){const code=new URLSearchParams(location.search).get('room')||'';app.innerHTML='<section class="card landing"><h2>Bring your people together.</h2><label>Your nickname<input id="name" maxlength="24" autocomplete="nickname" placeholder="e.g. Rinchen"></label><label>Join as<select id="role"><option value="player">Player · guess and compete</option><option value="viewer">Viewer · watch and react</option></select></label>'+btn('create','Create room','','primary')+'<p>Already have a room?</p><label>Room code<input id="code" maxlength="6" value="'+esc(code)+'" placeholder="ABC123" style="text-transform:uppercase"></label>'+btn('join','Join room')+'</section>'}
function ranks(s,full=false){return '<h3>'+(full?'Final rankings':'Round '+s.round+' rankings')+'</h3><div style="overflow:auto"><table class="ranks"><thead><tr><th>Rank</th><th>Player</th><th>Points</th><th>Correct speed</th>'+(full?'<th>✓ / ✕ / Skip / Miss</th>':'')+'</tr></thead><tbody>'+s.rankings.map(p=>'<tr><td>#'+p.rank+'</td><td>'+esc(p.name)+(p.id===s.winner?' 🏆':'')+'</td><td>'+p.score+'</td><td>'+(p.avgMs===null?'—':(p.avgMs/1000).toFixed(2)+'s')+'</td>'+(full?'<td>'+[p.stats.correct,p.stats.wrong,p.stats.skipped,p.stats.missed].join(' / ')+'</td>':'')+'</tr>').join('')+'</tbody></table></div><p class="small">Tied scores use average time on correct answers. Skips and wrong answers do not improve speed.</p>'}
function render(){if(!state)return landing();const saved=saveInputs(),s=state,me=s.members.find(m=>m.id===s.me);if(!me)return;const mgr=s.host===s.me||s.cohost===s.me,host=s.host===s.me,author=s.members.find(m=>m.id===s.author);let content='';
 if(s.phase==='lobby'){content='<h2>Get everyone ready.</h2><p>'+s.members.filter(m=>m.role==='player').length+'/8 players · '+s.members.filter(m=>m.role==='viewer').length+'/2 viewers · '+s.members.length+'/10 people</p>';if(mgr)content+='<form id="settings-form"><div class="settings"><label>Starting points<select id="points">'+[3,4,5,6].map(i=>'<option '+(s.settings.points===i?'selected':'')+'>'+i+'</option>').join('')+'</select></label><label>Guessing timer<select id="guessSeconds">'+[15,30,45,60].map(i=>'<option value="'+i+'" '+(s.settings.guessSeconds===i?'selected':'')+'>'+i+' seconds</option>').join('')+'</select></label></div><button class="quiet">Save settings</button></form>';else content+='<p>Starting points: '+s.settings.points+' · Guessing time: '+s.settings.guessSeconds+' seconds</p>';content+='<div class="controls section">';if(me.role==='player')content+=btn('ready',me.ready?'✓ Ready · undo':'I’m ready','','primary');else content+=btn('request',me.requested?'Promotion requested':'Request to play',me.requested?'disabled':'');if(mgr)content+=btn('start','Start game','','primary');content+='</div>';}
 if(s.phase==='write'){content='<div class="row"><div class="eyebrow">Round '+s.round+'</div><div class="timer" id="timer"></div></div><h2>'+(s.author===s.me?'It’s your turn!':esc(author?.name)+' is writing…')+'</h2>';if(s.author===s.me){content+='<p>Two truths first. Your lie goes in the red box.</p><form id="statement-form"><label>1 · Truth<textarea id="statement0" maxlength="200" required></textarea></label><label>2 · Truth<textarea id="statement1" maxlength="200" required></textarea></label><label class="lie-input">3 · Lie (automatically marked)<textarea id="statement2" maxlength="200" required></textarea></label><div class="controls"><button>Start guessing</button>'+btn('extend',s.extended?'Extension used':'Need more time · +30s',s.extended?'disabled':'')+'</div></form>';}else content+='<p>Get ready for three statements. The presenter has 90 seconds to write.</p>';}
 if(s.phase==='countdown')content='<h2>Get ready!</h2><p>'+esc(author?.name)+' started guessing. Keep your choices private.</p><div class="countdown" id="timer"></div>';
 if(['guess','reveal','finished'].includes(s.phase)){const finished=s.phase==='finished',reveal=s.phase!=='guess';if(finished){content='<div class="victory" role="status"><div class="eyebrow">LAST PLAYER STANDING</div><h2>VICTORY!</h2><div class="winner">'+esc(s.members.find(m=>m.id===s.winner)?.name||'No survivor')+'</div></div>'+ranks(s,true);}else content='<div class="row"><div class="eyebrow">Round '+s.round+' · '+esc(author?.name)+'’s statements</div>'+(!reveal?'<div id="timer" class="timer"></div>':'')+'</div><h2>'+(reveal?'The truth comes out.':'Which statement is the lie?')+'</h2>';if(!finished){s.statements.forEach((t,i)=>{const correct=reveal&&i===s.lie,wrong=reveal&&s.myResult?.type==='wrong'&&i===s.myVote;const label=correct?(s.myResult?.type==='correct'?'Correct · +1':'This was the lie'):wrong?'Wrong · −1':'';content+='<button class="choice '+(correct?'correct':wrong?'wrong':s.myVote===i?'selected':'')+'" data-choice="'+i+'" '+(!s.canGuess?'disabled':'')+'><span class="letter">'+String.fromCharCode(65+i)+'</span><span>'+esc(t)+(label?'<br><strong>'+label+'</strong>':'')+'</span></button>';});}
 if(!reveal){content+='<p class="small">'+s.answered+' / '+s.eligible+' responses received. Keep guesses private; presenter stays quiet.</p>';if(s.canGuess)content+=btn('skip','Skip · '+me.skips+' remaining',me.skips<1?'disabled':'');else if(s.myVote!==undefined)content+='<div class="notice">'+(s.myVote===null?'Skipped.':'Answer locked: '+esc(s.statements[s.myVote]))+'</div>';else content+='<p>'+ (me.away?'You’re away.':me.role==='viewer'?'You’re watching as a viewer.':me.score===0?'You’re eliminated.':s.author===s.me?'Stay quiet until the reveal.':'Waiting for the reveal.')+'</p>';}
 else{if(s.lieText)content+='<p><strong>The lie was:</strong> '+esc(s.lieText)+'</p>';if(s.myResult)content+='<div class="notice">'+esc(s.myResult.type[0].toUpperCase()+s.myResult.type.slice(1))+' · '+(s.myResult.delta>0?'+':'')+s.myResult.delta+' points</div>';content+='<div class="reactions">'+['😂','😮','👏','🔥','❤️','🤔'].map(e=>'<button data-emoji="'+e+'" aria-label="React '+e+'">'+e+'</button>').join('')+'</div><div class="reaction-feed">'+s.reactions.slice(-8).map(x=>'<span>'+esc(x.name)+' '+x.emoji+'</span>').join('')+'</div>';if(mgr)content+=btn(finished?'restart':'next',finished?'Back to lobby · rematch':'Next turn','','primary');else content+='<p class="small">Waiting for the host or co-host.</p>';}}
 if(s.phase==='roundEnd'){content='<h2>Round '+s.round+' complete</h2>'+ranks(s);if(mgr)content+=btn('next','Start round '+(s.round+1),'','primary');else content+='<p>Waiting for the host or co-host to start the next round.</p>';}
 const roles=m=>[m.id===s.host?'Host':null,m.id===s.cohost?'Co-host':null,m.role==='viewer'?'Viewer':m.score===0&&s.phase!=='lobby'?'Eliminated':'Player',m.away?'Away':null].filter(Boolean).map(badge).join('');
 const members=s.members.map(m=>'<div class="member"><div class="row"><div><span class="dot '+(!m.online?'off':'')+'"></span><strong>'+esc(m.name)+(m.id===s.me?' (you)':'')+'</strong><div>'+roles(m)+'</div><div class="small">'+(!m.online?'Disconnected':s.phase==='lobby'?(m.ready?'✓ Ready':m.role==='viewer'?'Watching':'Not ready'):'Connected')+'</div></div>'+(m.role==='player'&&s.phase!=='lobby'?'<div class="score">'+m.score+'</div>':'')+'</div>'+(mgr&&m.id!==s.me?'<div class="member-actions">'+(host&&m.id!==s.host?btn('cohost',m.id===s.cohost?'Remove co-host':'Make co-host','data-target="'+m.id+'"'):'')+(s.phase==='lobby'&&(m.role==='player'||m.requested)?btn('role',m.role==='player'?'Move to viewer':'Approve player','data-target="'+m.id+'" data-role="'+(m.role==='player'?'viewer':'player')+'"'):'')+(m.id!==s.host?btn('mute',m.muted?'Unmute chat':'Mute chat','data-target="'+m.id+'"')+btn('kick','Remove','data-target="'+m.id+'"','danger'):'')+'</div>':'')+(m.requested?'<div class="small">Requested promotion · before next game</div>':'')+'</div>').join('');
 const paused=['countdown','guess'].includes(s.phase);const chat='<details id="chat-panel" class="card chat"><summary>Room chat '+(paused?'· paused':'')+'</summary>'+(paused?'<p>Chat pauses while everyone guesses. Keep choices secret.</p>':'<div class="chatlog">'+s.chat.map(m=>'<div class="chatmsg">'+(m.system?'': '<strong>'+esc(m.name)+': </strong>')+esc(m.text)+'</div>').join('')+'</div><form id="chat-form"><input id="chat-text" maxlength="200" placeholder="'+(me.muted?'Chat muted':'Say something…')+'" '+(me.muted?'disabled':'')+' required aria-label="Chat message"><button '+(me.muted?'disabled':'')+'>Send</button></form>')+'</details>';
 app.innerHTML='<div class="card row"><div><div class="eyebrow">ROOM CODE</div><strong style="font-size:26px;letter-spacing:3px">'+s.code+'</strong> '+badge(s.locked?'Locked':s.playerFull?'Player seats full':'Open')+'</div><div class="controls">'+btn('invite','Copy invite')+(mgr?btn('lock',s.manualLock?'Unlock room':'Lock room'):'')+btn('away',me.away?'I’m back':'Away')+btn('leave','Leave','','danger')+'</div></div>'+(s.notice?'<div class="notice">'+esc(s.notice)+'</div>':'')+(me.role==='player'&&s.phase!=='lobby'?'<p class="small">'+me.skips+' skip'+(me.skips===1?'':'s')+' remaining this round.'+(me.skips===0?' No skips left: missing an answer costs −1.':'')+'</p>':'')+'<div class="grid"><section class="card">'+content+'</section><aside><section class="card"><h3>The room</h3>'+members+'</section>'+chat+'</aside></div>';
 const oldKey=render.key;const newKey=s.phase+':'+s.turnId;if(oldKey===newKey)restoreInputs(saved);else{const persistent={values:{'chat-text':saved.values['chat-text']??''},details:saved.details};restoreInputs(persistent)}render.key=newKey;tickDisplay();}
function tickDisplay(){const el=$('#timer');if(el&&state){const sec=Math.max(0,Math.ceil((state.deadline-Date.now()-offset)/1000));el.textContent=state.phase==='countdown'?sec:sec+'s'}}setInterval(tickDisplay,100);
function reset(){session=null;state=null;lastTurn=null;lastPhase=null;sessionStorage.removeItem('party-session-v2');$('#connection').textContent='';landing()}
app.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled||pending)return;try{pending=true;if(b.dataset.choice!==undefined){await request('vote',{choice:Number(b.dataset.choice)});return}if(b.dataset.emoji){await request('react',{emoji:b.dataset.emoji});return}const a=b.dataset.action;if(!a)return;if(a==='invite'){const link=location.origin+location.pathname+'?room='+state.code;try{await navigator.clipboard.writeText('Join my Two Truths & a Lie room: '+link+' · Code '+state.code);$('#error').textContent='Invite copied!';}catch{prompt('Copy this invitation:',link+' · Code '+state.code)}return}if(a==='leave'){if(!confirm('Leave this room? Your player seat and score will be removed.'))return;await request('leave');reset();return}if(a==='kick'&&!confirm('Remove this person from the room?'))return;if(a==='create'||a==='join'){await request(a,{name:$('#name').value,role:$('#role').value,code:$('#code').value.trim().toUpperCase()});return}let extra={};if(a==='skip'){await request('vote',{choice:null});return}if(b.dataset.target)extra.target=b.dataset.target;if(a==='cohost'&&state.cohost===extra.target)extra.target=null;if(a==='role')extra.role=b.dataset.role;await request(a,extra);}catch(e){$('#error').textContent=e.message}finally{pending=false}});
app.addEventListener('submit',async e=>{e.preventDefault();if(pending)return;try{pending=true;if(e.target.id==='statement-form')await request('submit',{statements:[0,1,2].map(i=>$('#statement'+i).value)});else if(e.target.id==='settings-form')await request('settings',{points:Number($('#points').value),guessSeconds:Number($('#guessSeconds').value)});else if(e.target.id==='chat-form'){const text=$('#chat-text').value;await request('chat',{text});$('#chat-text').value='';}}catch(e){$('#error').textContent=e.message}finally{pending=false}});
async function poll(){if(!session||polling||pending)return;polling=true;try{await request('poll',{},true)}catch(e){if(/session ended|not found/.test(e.message)){reset();$('#error').textContent=e.message}else{$('#connection').textContent='Connection lost · retrying…';network=false}}finally{polling=false}}setInterval(poll,1200);if(session){app.innerHTML='<section class="card">Rejoining your room…</section>';poll()}else landing();
window.addEventListener('beforeunload',e=>{if(session&&state&&!['lobby','finished'].includes(state.phase)){e.preventDefault();e.returnValue=''}});
